jobs: 5000
use-conda: true
immediate-submit: false
notemp: true
restart-times: 5
jobscript: "slurm-jobscript.sh"
cluster: "./config/slurm.cemm/slurm-submit.py {dependencies}"
cluster-status: "slurm-status.py"
max-jobs-per-second: 10
max-status-checks-per-second: 10
local-cores: 1
latency-wait: 120
